- platform: template
  switches:
    lounge_lights_off:
      value_template: "{{ is_state('group.lounge_main_lights', 'on') }}"
      turn_on:
        service: light.turn_on
        data:
          entity_id: group.lounge_main_lights
      turn_off:
        service: light.turn_off
        data:
          entity_id: group.lounge_main_lights
- platform: mqtt
  name: "Zigbee2mqtt Main join"
  state_topic: "zigbee2mqtt/bridge/config/permit_join"
  command_topic: "zigbee2mqtt/bridge/config/permit_join"
  payload_on: "true"
  payload_off: "false"
- platform: flux
  lights:
    - light.blueroom_lamp
    - light.lounge_lights
    - light.kitchen_lights
    - light.kitchen_island
    - light.lounge_2
    - light.mid
    - light.loungelamp_light
    - light.upstairs_lights
    - light.mike_and_carmen_s_room
  name: Fluxer
  start_time: '7:00'
  stop_time: '23:00'
  start_colortemp: 6500
  sunset_colortemp: 3500
  stop_colortemp: 2700
  disable_brightness_adjust: true